### ISSUE TITLE
Apple UUID

### ISSUE THREAD

**Issue by axoroll7** [wdes/mail-autodiscover-autoconfig#1]
I have read online, since iOS v15+, the number of configuration files sharing the same payload is limited.
The old scripts found online should not work anymore.
In your doc, you mentioned that a random UUID should work. Unfortunately, I do not have an iOS/iPad phone/tablet to test it.
But I do not think a random UUID would work, because I think the UUID is a part of a signature. Have you tested this functionality ? I do not have any source to present, I did my research some time ago. If it works, it would be perfect for some clients who do not like the manual configurations in Apple Mail.

Side note : Your project is fabulous 🔥

**Comment by williamdes** [comment]
> Side note : Your project is fabulous 🔥

Thank you!!!

I tested the profile on an Apple device and it worked fine ;) 

This project lacks a README example of a docker compose to run it 
I will push this tomorrow 
It works fine in production since the launch

**Comment by williamdes** [comment]
Edit: I already did,  so feel free to complain about any aspect of this project for improvements

**Comment by axoroll7** [comment]
Thank you !
I will close the issue.

**Comment by williamdes** [comment]
>But I do not think a random UUID would work, because I think the UUID is a part of a signature. 

Just re reading this, I did not implement the signature so it shows as untrusted. I lack a permanent testing device to play with apple stuff. Not sure if it is worth the time just to provide a file that is signed vs a non signed file with a little red sentence

**Comment by axoroll7** [comment]
> >But I do not think a random UUID would work, because I think the UUID is a part of a signature. 
> 
> Just re reading this, I did not implement the signature so it shows as untrusted. I lack a permanent testing device to play with apple stuff. Not sure if it is worth the time just to provide a file that is signed vs a non signed file with a little red sentence 

My assumptions : A non-trusted mobileconfig file have big drawbacks, like uninstalling itself after a while (maybe), signing the file would require a paid certificate with a renew bot, and two autodiscover servers cannot share the same mobileconfig file. It is difficult to find recent informations about all of this.

**Comment by axoroll7** [comment]
Personally, on my software server (much less complete than yours), I discarded Apple completely.

**Comment by williamdes** [comment]
> Personally, on my software server (much less complete than yours), I discarded Apple completely.

Do you have other softwares that I can test my server on?

**Comment by williamdes** [comment]
Just tested with some of the latest Apple softwares, see: 1a7d841443f3bc815b7ae3199ac69e58ec616fc2

**Comment by axoroll7** [comment]
> > Personally, on my software server (much less complete than yours), I discarded Apple completely.
> 
> Do you have other softwares that I can test my server on? 

Have you tested K-9 Mail on Android ? It will become Thunderbird Mobile.

Edit:
It should work with K-9 Mail :
```kotlin
            return HttpUrl.Builder()
                .scheme("https")
                .host(domain)
                .addEncodedPathSegments(".well-known/autoconfig/mail/config-v1.1.xml")
                .addQueryParameter("emailaddress", email)
                .build()
```
[Line 31](https://github.com/thundernest/k-9/blob/9cf73c99d09332a461ecb3830db86bca044bdf2e/app/autodiscovery/thunderbird/src/main/java/com/fsck/k9/autodiscovery/thunderbird/ThunderbirdAutoconfigFetcher.kt)

**Comment by williamdes** [comment]
It does not work because they call the fallback and do not try the autoconfig domain first..
I will open an issue about it. Ref: https://wiki.mozilla.org/Thunderbird:Autoconfiguration

**Comment by williamdes** [comment]
Done: https://github.com/thundernest/k-9/issues/6250

**Comment by axoroll7** [comment]
@williamdes
> It does not work because they call the fallback and do not try the autoconfig domain first.. I will open an issue about it. Ref: https://wiki.mozilla.org/Thunderbird:Autoconfiguration

I though myself to open an issue about it, but I preferred to consider using a reverse proxy to make cohabit my web server and my autoconfig/autodiscover server. I consider it a temporary solution.
