### ISSUE TITLE
Tested email clients behavior

### ISSUE THREAD

**Issue by axoroll7** [wdes/mail-autodiscover-autoconfig#4]
Does Android Nine prefix its request with `/v1.1/` ?
Does Android MyMail and others send a GET request instead of a POST request to the URL `/autodiscover/autodiscover.xml` ?
Does Android Nine use the JSON API of Autodiscover but not the XML API ?

It was implicitly stated by your code comments, but I wanted to confirm this.

Thank you again for your project !

Edit: typo

**Comment by williamdes** [comment]
Hi @axoroll7 !
> Does Android Nine prefix its request with /v1.1/ ?

Yes, I double checked right now. They did an implementation mistake. I think I have wrote to them about it. So I am basically the only folk that will support their autodiscovery 😄 

> Does Android MyMail and others send a GET request instead of a POST request to the URL /autodiscover/autodiscover.xml ?

If my comments say so, then it is how it is. Or maybe I did a mistake, but I will only re try all this in one year or two because of how much time it takes to install, test, and uninstall all possible apps on the planet 😄 

Here is the log
```
GET /autodiscover/autodiscover.json?Email=williamdes%40wdes.fr&Protocol=ActiveSync&RedirectCount=1:
   >> Matched: (post_mail_autodiscover_microsoft_json) GET /autodiscover/autodiscover.json?<Email>&<Protocol>&<RedirectCount>
   >> Outcome: Success
   >> Response succeeded.
GET /v1.1/mail/config-v1.1.xml?emailaddress=williamdes@wdes.fr:
   >> Matched: (v11_mail_config_v11) GET /v1.1/mail/config-v1.1.xml?<emailaddress>
   >> Outcome: Success
   >> Response succeeded.
```

> It was implicitly stated by your code comments, but I wanted to confirm this.

Sure, I am happy to see that someone did like my time consuming comments

> Thank you again for your project !

I am bery happy to have nice feedback, spread the word about the project :p

**Comment by williamdes** [comment]
Feel free to install Apps and let me know if they use some URLs.

Just added one more Android app: fbe51ddece71de17eec49a612472e621df8300c3

I need to figure out why BlueMail uses`/autodiscover/autodiscover.svc` route asking for `text/xml`

Edit: it sends:
```xml
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:a="http://schemas.microsoft.com/exchange/2010/Autodiscover" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><a:RequestedServerVersion>Exchange2010</a:RequestedServerVersion><wsa:Action>http://schemas.microsoft.com/exchange/2010/Autodiscover/Autodiscover/GetUserSettings</wsa:Action><wsa:To>https://autodiscover.wdes.fr/autodiscover/autodiscover.svc</wsa:To></soap:Header><soap:Body><a:GetUserSettingsRequestMessage xmlns:a="http://schemas.microsoft.com/exchange/2010/Autodiscover"><a:Request><a:Users><a:User><a:Mailbox>williamdes@wdes.fr</a:Mailbox></a:User></a:Users><a:RequestedSettings><a:Setting>ExternalEwsUrl</a:Setting></a:RequestedSettings></a:Request></a:GetUserSettingsRequestMessage></soap:Body></soap:Envelope>
```

Edit: I will not code for that, it's useless as it only returns an endpoint URL.
See Microsoft docs: https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/main/docs/exchange-web-services/how-to-get-domain-settings-from-an-exchange-server.md#get-user-settings-by-using-ews-soap-autodiscover

**Comment by axoroll7** [comment]
@williamdes 

OK, it seems this email client asks for an end-point. Your reflection leads me to think about Outlook :

If I understand correctly, your code is compatible with POX (Plain Old XML), through "autodiscover.xml" naturally, and through "autodiscover.json" with a redirection from AutodiscoverV2 to AutodiscoverV1. 
SOAP seems highly more complex to implement. The main concern here, is to be compatible with Outlook. The latest Outlooks. I do not know how Outlook works exactly, but if POX is read by Acompli servers, there is no need to implement SOAP ? I did not test it. Zoho mail and OVH email accounts are compatible with Outlook, because I saw it. I will try to send them some SOAP requests to see how they perform, to test my theory.

Edit : I should look into the mobilesync thing too, maybe.

**Comment by axoroll7** [comment]
I am stupid. Acompli does its autodiscover lookup on the MX domain. I had forgotten. I need sleep, sorry.
I am still going to do a SOAP request on the OVH and Zoho Mail servers, by curiosity. If it does not work, I see absolutely no need to implement SOAP, even if some email clients use it.

Edit : I take back what I said, my last sentence. We never know.

Edit 2 : My reflection leads me to a dead-end. I should stop thinking right now, people reading can forget everything I said. My thoughts will not give us an email client's support, in particular Outlook. Only people who can access their SMTP server's hostname, and add an autodiscover file, have to know they can use POX with no problem.

Edit 3 : A bit of clarification : Acompli does first, an autodiscover lookup on the MX domain. Then, if the autodiscover failed, it does an autodiscover on the domain of your email address. The two lookups are performed through SOAP, and POX. So, this GitHub project works perfectly. If it does not work, it is because your SMTP server takes precedence.

**Comment by williamdes** [comment]
Thank you for sharing your thoughts, it's interesting

I think that we could bring more support for Outlook's new mobilesync and all this stuff.
I need to discuss with https://github.com/StephanvanSchaik/automail/issues/1
Maybe we can merge the projects and build something awesome
